inherit: 
    - models/custom.yaml

    # - models/demb128_nl4_nh2.yaml
    # - models/demb128_nl12_nh4.yaml
    # - models/demb64_nl8_nh1.yaml
    # - models/demb64_nl6_nh1.yaml
    # - models/demb64_nl4_nh1.yaml
    # - models/demb64_nl16_nh2.yaml
    # - models/demb32_nl8_nh1.yaml
    # - models/demb32_nl6_nh1.yaml
    # - models/demb32_nl10_nh1.yaml
    # - models/demb32_nl24_nh1.yaml

    # - models/demb32_nl12_nh1.yaml
    # - models/demb64_nl12_nh2.yaml

    # - models/demb256_nl4_nh8.yaml
    # - models/demb256_nl6_nh8.yaml
    # - models/demb256_nl8_nh8.yaml
    # - models/demb256_nl10_nh8.yaml

    # - wandb.yaml

model:
    n_dims: 5
    n_positions: 101
    pos_encode: True

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    eval_every_steps: 1000
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
